In [8]:
import pandas as pd

In [9]:
df = pd.read_csv('train.csv')
df

,id,subject,email,spam
0,0,Subject: A&L Daily to be auctioned in bankrupt...,URL: http://boingboing.net/#85534171\n Date: N...,0
1,1,"Subject: Wired: ""Stronger ties between ISPs an...",URL: http://scriptingnews.userland.com/backiss...,0
2,2,Subject: It's just too small ...,<HTML>\n <HEAD>\n </HEAD>\n <BODY>\n <FONT SIZ...,1
3,3,Subject: liberal defnitions\n,Depends on how much over spending vs. how much...,0
4,4,Subject: RE: [ILUG] Newbie seeks advice - Suse...,hehe sorry but if you hit caps lock twice the ...,0
...,...,...,...,...
8343,8343,Subject: Re: ALSA (almost) made easy\n,"Thanks for this, I'm going to give them anothe...",0
8344,8344,Subject: Re: Goodbye Global Warming\n,Thanks for the link - I'm fascinated by archae...,0
8345,8345,Subject: hello\n,WE NEED HELP. We are a 14 year old fortune 50...,1
8346,8346,Subject: Your application is below. Expires Ju...,<html>\n \n \n <HEAD> \n <META charset=3DUTF-8...,1
8347,8347,Subject: Re: [SAtalk] CONFIDENTIAL\n,"On Wed, 2002-08-21 at 06:42, Craig R.Hughes wr...",0

In [10]:
test_df = pd.read_csv('test.csv')
test_df

,id,subject,email
0,0,Subject: CERT Advisory CA-2002-21 Vulnerabilit...,\n \n -----BEGIN PGP SIGNED MESSAGE-----\n \n ...
1,1,Subject: ADV: Affordable Life Insurance ddbfk\n,Low-Cost Term-Life Insurance!\n SAVE up to 70%...
2,2,Subject: CAREER OPPORTUNITY. WORK FROM HOME\n,------=_NextPart_000_00A0_03E30A1A.B1804B54\n ...
3,3,Subject: Marriage makes both sexes happy\n,"URL: http://www.newsisfree.com/click/-3,848315..."
4,4,Subject: Re: [SAtalk] SA very slow (hangs?) on...,On Thursday 29 August 2002 16:39 CET Mike Burg...
...,...,...,...
995,995,Subject: Re: Alsa/Redhat 8 compatability\n,"Once upon a time, Brian wrote :\n \n > \n > ..."
996,996,Subject: Re: Goodbye Global Warming\n,\n --]> A Green once said that if the Spotted ...
997,997,Subject: Re: Entrepreneurs\n,"On Fri, 23 Aug 2002, Robert Harley wrote:\n \n..."
998,998,Subject: Re: [ILUG] slashdot EW Dijkstra humor\n,JPL suggested:\n > Recursion is only truely u...
999,999,Subject: [ILUG-Social] Everybody Gets Paid - N...,Everybody gets paid. No recruiting required.\...

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8348 entries, 0 to 8347
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       8348 non-null   int64
 1   subject  8342 non-null   str
 2   email    8348 non-null   str
 3   spam     8348 non-null   int64
dtypes: int64(2), str(2)
memory usage: 261.0 KB

In [12]:
df.head()

,id,subject,email,spam
0,0,Subject: A&L Daily to be auctioned in bankrupt...,URL: http://boingboing.net/#85534171\n Date: N...,0
1,1,"Subject: Wired: ""Stronger ties between ISPs an...",URL: http://scriptingnews.userland.com/backiss...,0
2,2,Subject: It's just too small ...,<HTML>\n <HEAD>\n </HEAD>\n <BODY>\n <FONT SIZ...,1
3,3,Subject: liberal defnitions\n,Depends on how much over spending vs. how much...,0
4,4,Subject: RE: [ILUG] Newbie seeks advice - Suse...,hehe sorry but if you hit caps lock twice the ...,0

In [13]:
df.isna().sum()

id         0
subject    6
email      0
spam       0
dtype: int64

In [14]:
df['text'] = df['subject'].fillna('') + df['email'].fillna('')
test_df['text'] = test_df['subject'].fillna('') +test_df['email'].fillna('')

In [15]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'<.*?>', '', text)  # Remove HTML tags
    text = re.sub(r'[^a-z\s]', '', text)  # Remove non-alphabet characters
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df['clean_text'] = df['text'].apply(clean_text)
test_df['clean_text'] = test_df['text'].apply(clean_text)

In [16]:
df['spam'].value_counts()

spam
0    6208
1    2140
Name: count, dtype: int64

In [17]:
df.columns

Index(['id', 'subject', 'email', 'spam', 'text', 'clean_text'], dtype='str')

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()

vectorizer = TfidfVectorizer(
    max_features=5000,    
    ngram_range=(1, 2)    
)

In [19]:
from sklearn.model_selection import train_test_split

X = vectorizer.fit_transform(df['clean_text'])
y = df['spam']

X_train, X_val, y_train, y_val = train_test_split(
    X, y,
    test_size=0.2,       
    random_state=42,
    stratify=y           
)

In [20]:
# from sklearn.linear_model import LogisticRegression
# from sklearn.metrics import classification_report

# model = LogisticRegression(max_iter=1000)
# model.fit(X_train, y_train)
# preds = model.predict(X_val)


# print(classification_report(y_val,preds))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99      1242
           1       0.96      0.95      0.96       428

    accuracy                           0.98      1670
   macro avg       0.97      0.97      0.97      1670
weighted avg       0.98      0.98      0.98      1670

In [30]:
from sklearn.naive_bayes import MultinomialNB

nb_model = MultinomialNB()
nb_model.fit(X_train, y_train)

preds = nb_model.predict(X_val)
print(classification_report(y_val,preds))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98      1242
           1       0.93      0.95      0.94       428

    accuracy                           0.97      1670
   macro avg       0.96      0.96      0.96      1670
weighted avg       0.97      0.97      0.97      1670

We find that the logistic regression model is doing good so we further hypertune it but since it is an NLP task we better move forward with naive bayes

In [25]:
param_grid = {
    'C': [0.01, 0.1, 1, 10],          
    'solver': ['liblinear', 'lbfgs'],
    'penalty': ['l2'],                
    'max_iter': [100, 200, 500]
}

In [26]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
grid_search = GridSearchCV(model, param_grid, cv=5, scoring='f1', n_jobs=-1, verbose=1)
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

c:\Users\Acer\Desktop\ai-ml project\Gmail-spam-filter\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(

GridSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1, 10], 'max_iter': [100, 200, 500],
                         'penalty': ['l2'], 'solver': ['liblinear', 'lbfgs']},
             scoring='f1', verbose=1)

In [27]:
print( grid_search.best_params_)
print( grid_search.best_score_)

{'C': 10, 'max_iter': 100, 'penalty': 'l2', 'solver': 'lbfgs'}
0.9782655256966699

In [28]:
model = LogisticRegression(C=10, max_iter=100, penalty='l2', solver='liblinear')
model.fit(X_train,y_train)

c:\Users\Acer\Desktop\ai-ml project\Gmail-spam-filter\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(

LogisticRegression(C=10, penalty='l2', solver='liblinear')

In [29]:
preds = model.predict(X_val)

from sklearn.metrics import accuracy_score
accuracy_score(y_val, preds)

0.988622754491018

### Hypertuning the naive bayes model

In [31]:
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

param_grid = {
    'alpha': [0.01, 0.1, 0.5, 1.0],
    'fit_prior': [True, False]
}

nb_model = MultinomialNB()
grid_search = GridSearchCV(nb_model, param_grid, cv=5, scoring='f1', n_jobs=-1, verbose=1)
grid_search.fit(X_train, y_train)

print(grid_search.best_params_)
print(grid_search.best_score_)

model = grid_search.best_estimator_
preds = model.predict(X_val)
accuracy_score(y_val, preds)

Fitting 5 folds for each of 8 candidates, totalling 40 fits
{'alpha': 0.01, 'fit_prior': False}
0.9564005920420542

0.9784431137724551

In [33]:
test_df

,id,subject,email,text,clean_text
0,0,Subject: CERT Advisory CA-2002-21 Vulnerabilit...,\n \n -----BEGIN PGP SIGNED MESSAGE-----\n \n ...,Subject: CERT Advisory CA-2002-21 Vulnerabilit...,subject cert advisory ca vulnerability in php ...
1,1,Subject: ADV: Affordable Life Insurance ddbfk\n,Low-Cost Term-Life Insurance!\n SAVE up to 70%...,Subject: ADV: Affordable Life Insurance ddbfk\...,subject adv affordable life insurance ddbfk lo...
2,2,Subject: CAREER OPPORTUNITY. WORK FROM HOME\n,------=_NextPart_000_00A0_03E30A1A.B1804B54\n ...,Subject: CAREER OPPORTUNITY. WORK FROM HOME\n...,subject career opportunity work from home next...
3,3,Subject: Marriage makes both sexes happy\n,"URL: http://www.newsisfree.com/click/-3,848315...",Subject: Marriage makes both sexes happy\nURL:...,subject marriage makes both sexes happy url ht...
4,4,Subject: Re: [SAtalk] SA very slow (hangs?) on...,On Thursday 29 August 2002 16:39 CET Mike Burg...,Subject: Re: [SAtalk] SA very slow (hangs?) on...,subject re satalk sa very slow hangs on this m...
...,...,...,...,...,...
995,995,Subject: Re: Alsa/Redhat 8 compatability\n,"Once upon a time, Brian wrote :\n \n > \n > ...",Subject: Re: Alsa/Redhat 8 compatability\nOnce...,subject re alsaredhat compatability once upon ...
996,996,Subject: Re: Goodbye Global Warming\n,\n --]> A Green once said that if the Spotted ...,Subject: Re: Goodbye Global Warming\n\n --]> A...,subject re goodbye global warming a green once...
997,997,Subject: Re: Entrepreneurs\n,"On Fri, 23 Aug 2002, Robert Harley wrote:\n \n...","Subject: Re: Entrepreneurs\nOn Fri, 23 Aug 200...",subject re entrepreneurs on fri aug robert har...
998,998,Subject: Re: [ILUG] slashdot EW Dijkstra humor\n,JPL suggested:\n > Recursion is only truely u...,Subject: Re: [ILUG] slashdot EW Dijkstra humor...,subject re ilug slashdot ew dijkstra humor jpl...
999,999,Subject: [ILUG-Social] Everybody Gets Paid - N...,Everybody gets paid. No recruiting required.\...,Subject: [ILUG-Social] Everybody Gets Paid - N...,subject ilugsocial everybody gets paid no recr...

In [34]:
X_test = vectorizer.transform(test_df['clean_text'])
results = model.predict(X_test)

In [35]:
submission_df = pd.DataFrame(zip(test_df["id"], results), columns=["id", "Class"])
submission_df["Class"] = submission_df["Class"].astype(int)
submission_df.to_csv("submission.csv", index=False)

In [37]:
submission_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      1000 non-null   int64
 1   Class   1000 non-null   int64
dtypes: int64(2)
memory usage: 15.8 KB

In [38]:
import joblib

joblib.dump(model, 'spam_model.pkl')
joblib.dump(vectorizer, 'vectorizer.pkl')

['vectorizer.pkl']